### ISSUE TITLE
Add Python 3 Support

### ISSUE THREAD

**Issue by oubiwann** [robbielynch/ierlang#6]
Python 3 is pretty much all I use these days. I'll give it a whirl and see if any issues pop up.

**Comment by robbielynch** [comment]
Finally, support has been added for python3.4.*

The solution is pretty hacky, and not pretty on the eye.

I added 
```
EMPTY_BYTE_STRING=\`python3 -c "print(''.encode())"`
```
to the makefile. Because the problem with python3 treats command line strings as Strings, where as Python2 treats them as byte strings. IPython only accepts byte strings.

```
--Session.key=$(EMPTY_BYTE_STRING) \
--Session.keyfile=$(EMPTY_BYTE_STRING)
```

So it's a round-about way of getting the byte string. Not ideal, but it works.
